### PR TITLE
into

### PR DESCRIPTION
**Pull request by bonega**

### CODE REVIEW

**Comment by borkdude** [comment]
@bonega Thanks! Could you add a test for every arity?

**Comment by bonega** [comment]
@borkdude sure, pushed now.
The js-tests are a bit finicky regarding clean.

**Comment by bonega** [comment]
@borkdude sorry, was taking a break.
Will check style doc for next PR.

**Comment by borkdude** [comment]
np, it was only a minor detail that was easy to fix. thanks for your contribution! it's now visible at:
https://re-find.it/?args=%5B1%202%203%5D%20%5B4%205%206%5D&ret=%5B1%202%203%204%205%206%5D&exact=true

**Pull request merged**
