### PR TITLE
Add specs for clojure.set #70

### PR DESCRIPTION
**Pull request by eerohele**
This is the first cut; a starting point.

TODO / questions:

- [x] Sign CA
- [x] Should non-set args be allowed?
- [x] Run against coal mine?
- [x] Naming (e.g. `::nilable-seqable-of-map-entry`, while descriptive, is a bit of a mouthful)
- [x] Unit tests: does checking return values make sense or does `check-call` suffice?

With regard to question 2, there's been some discussion under #46 and #70, but maybe we should consolidate the salient points here. The current version disallows non-set args, but I'll modify the code accordingly if necessary.

Running coal mine tests would be useful, but I haven't yet investigated how that's done.

### CODE REVIEW

**Comment by borkdude** [comment]
About coal-mine:

    script/coal-mine

runs a random problem set from the coal-mine corpus.

    script/coal-mine nth 0

runs the `nth` coal-mine problem.

As some problems can take a long time while instrumented, there is also the option to set the `COAL_MINE_TIMEOUT` environment variable, so the test exits after a maximum amount of seconds.

To run a selection of coal-mine tests:

    clj -A:test:coal-mine-runner-clj(s)

and change `speculative.coal-mine-runner` to the tests you want.

To run ALL coal-mine tests (this can take a looong time):

    clj -A:test:coal-mine-clj(s)

**Comment by borkdude** [comment]
About `check-call`: it checks `:args`, `:ret` and `:fn` specs. The test should test that it doesn't throw on valid input. Checking for the return value is optional, but good: this way we can also detect failures in future clojure(script) versions.

**Comment by borkdude** [comment]
About `::nilable-seqable-of-map-entry`, as `seqable?` already accepts `nil`, the `nilable` part of the name is superfluous.

**Comment by eerohele** [comment]
`::nilable-seqable-of-map-entry` is actually a mistake since it's inaccurate. The spec is `(s/nilable (s/coll-of ::ss/seqable-of-map-entry))`, so it should be `::nilable-coll-of-seqable-of-map-entry`, which is… well.

The clojure.set parameter names use `rel`, which makes sense and is succint. Maybe `::rel*`…? That isn't very descriptive, though.

**Comment by borkdude** [comment]
@eerohele Since you're using this spec for `rel` arguments, why not just call it `::rel`.

**Comment by eerohele** [comment]
I'm already using `::rel`:

```clojure
(s/def ::rel
  (s/nilable (s/coll-of ::nilable-map)))
```

Not all set functions that accept `::rel` accept `::nilable-coll-of-seqable-of-map-entry`.

**Comment by borkdude** [comment]
See my EDIT. You're fast :).

**Comment by slipset** [comment]
@eerohele Thanks a lot for this, this is huge! 
If you could squash all the commits into one, I'd be super happy.

**Comment by borkdude** [comment]
@slipset Github has a "squash and merge" button?

**Pull request merged**
