### PR TITLE
Style guide proposal

### PR DESCRIPTION
**Pull request by borkdude**
@slipset @mfikes Feel free to disagree and discuss.

### CODE REVIEW

**Comment by borkdude** [comment]
@puredanger

I specifically wanted a consistent style for the arity names.
Sometimes we use `:binary`, `:trinary`, ... I personally thing `:arity-0`, `:arity-1` is easier and more clear. 

Sometimes different arities have different result types. E.g. the `:arity-2` of `map` returns `::transducer`, the `:arity-3` of `map` returns a `seqable?`. When you use these alternatives (using `s/alt`), you can use this in a `:fn` spec to decide what the return predicate should be? Don't know if that's useful though.

About sorting/grouping: anything that doesn't make the order random is fine by me. Maybe we can order them by how they appear in clojure.clore more or less.

**Comment by borkdude** [comment]
@puredanger Updated.

**Comment by puredanger** [comment]
I think the seq/transducer case is one where separating the arities is potentially useful (although in that case they have different functional uses, so I'd prefer meaningful names to arity-1). The best way to establish a relationship between args and ret is by adding a fn spec. The fn spec can verify that the args match the ret in the seq and transducer cases. Something like:

```clojure
(s/fdef clojure.core/map
  :args (s/alt :transducer (s/cat :xf ifn?)
               :seq (s/cat :f ifn? :colls (s/+ seqable?)))
  :ret (s/or :transducer ifn? :seq seqable?)
  :fn (fn [{:keys [args ret]}]
        (= (key args) (key ret))))
```

**Comment by borkdude** [comment]
@puredanger Good points. How can you choose more meaningful names in this spec? 

```
(s/fdef clojure.core/range
  :args (s/or :arity-0 nil?
              :arity-1 (s/cat :end number?)
              :arity-2 (s/cat :start number? :end? number?)
              :arity-3 (s/cat :start number? :end number? :step number?))
  :ret seqable?)
```

**Comment by puredanger** [comment]
There are a variety of ways to do range, but here's one idea:

```clojure
user=> (s/def ::range-args (s/alt :infinite (s/cat) :finite (s/cat :start (s/? number?) :end number? :step (s/? number?))))
:user/range-args
user=> (s/conform ::range-args [])
[:infinite {}]
user=> (s/conform ::range-args [1])
[:finite {:end 1}]
user=> (s/conform ::range-args [1 10])
[:finite {:start 1, :end 10}]
user=> (s/conform ::range-args [1 10 2])
[:finite {:start 1, :end 10, :step 2}]
```

**Comment by borkdude** [comment]
Excellent! Updated the styleguide to reflect this.

**Pull request merged**
