### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by slipset** [comment]
Seems like @mfikes beat you to it.
I believe @mfikes implementation is somewhat more correct, but I'd really appreciate the tests
If you could resolve the conflicts, I'd be happy to merge!

**Comment by borkdude** [comment]
@slipset Ready merge.
@mfikes I renamed to tests file to cljc. Any suggestion on how to run it?

**Comment by mfikes** [comment]
@borkdude Run tests via `clj -A:test:runner`

**Comment by borkdude** [comment]
@mfikes Sorry, I mean specifically for clojurescript.

**Comment by borkdude** [comment]
@mfikes I got the tests working using `plk` now. I have to run as follows:

```
plk -A:test -e "(require '[clojure.test :as t])" -e "(require '[speculative.core-test])" -e "(t/run-tests 'speculative.core-test)"
```

**Comment by slipset** [comment]
Sorry, @mfikes beat you to it again :/
I'll try to take all PR's into considerations before merging in the future.

**Comment by slipset** [comment]
rebased and stuff locally

**Pull request closed without merging**
